--- # copy ssh keys
- hosts: dbsystems
  become: yes
  tasks:
  - name: copy ssh keys to remote hosts
    copy:
      src: /home/ansible/keys/supervisor/authorized_keys
      dest: /home/supervisor/authorized_keys
      owner: supervisor
      group: supervisor
      mode: 0600
  - name: copy ssh keys to remote hosts
    copy:
      src: /home/ansible/keys/home/consultant/authorized_keys
      dest: /home/consultant/authorized_keys
      owner: consultant
      group: consultant
      mode: 0600
 
