--- # reports.yml
- hosts: node1
  become: yes
  tasks:
  - name: download  http://apps.l33t.com/transaction_list
    block:
      - get_url:
          url:  http://apps.l33t.com/transaction_list
          dest: /home/ansible/transaction-list
      - replace:
          path: /home/ansible/transaction_list 
          regexp: "#BLANKLINE"
          replace: '\n'
      - debug:
          msg: "file downloaded"
    rescue:
      - debug:
          msg: "l33t.com appears to be down.  Try again later."
    always:
      - debug:
          msg: "Attempt completed"
